name: Deploy creative-session to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print directory contents
        run: |
          ls
          pwd

      - name: Deploy creative-session to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: main
          folder: .
          token: ${{ secrets.GH_PAGES_TOKEN }}
