name: publish-pixi-lib-to-npm
on:
  push:
    branches:
      - main
    paths:
      - 'creative-session/4-pixi/2-pixi-lib'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Increment version
        run: node increment-version.js

      - name: Build library
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_LIB_PUBLISH }}
