name: Deploy task-app to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - '7-react/3-task-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and build the app
        working-directory: 7-react/3-task-app
        run: |
          npm ci
          npm run build

      - name: Print directory contents
        run: |
          ls
          pwd
